package com.dixon.bookkeeping.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dixon.bookkeeping.bean.DayItemBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DAY_ITEM_BEAN".
*/
public class DayItemBeanDao extends AbstractDao<DayItemBean, Long> {

    public static final String TABLENAME = "DAY_ITEM_BEAN";

    /**
     * Properties of entity DayItemBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property TimeDesc = new Property(1, String.class, "timeDesc", false, "TIME_DESC");
        public final static Property InOrOut = new Property(2, boolean.class, "inOrOut", false, "IN_OR_OUT");
        public final static Property Amount = new Property(3, long.class, "amount", false, "AMOUNT");
    }


    public DayItemBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DayItemBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DAY_ITEM_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"TIME_DESC\" TEXT," + // 1: timeDesc
                "\"IN_OR_OUT\" INTEGER NOT NULL ," + // 2: inOrOut
                "\"AMOUNT\" INTEGER NOT NULL );"); // 3: amount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DAY_ITEM_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DayItemBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String timeDesc = entity.getTimeDesc();
        if (timeDesc != null) {
            stmt.bindString(2, timeDesc);
        }
        stmt.bindLong(3, entity.getInOrOut() ? 1L: 0L);
        stmt.bindLong(4, entity.getAmount());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DayItemBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String timeDesc = entity.getTimeDesc();
        if (timeDesc != null) {
            stmt.bindString(2, timeDesc);
        }
        stmt.bindLong(3, entity.getInOrOut() ? 1L: 0L);
        stmt.bindLong(4, entity.getAmount());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public DayItemBean readEntity(Cursor cursor, int offset) {
        DayItemBean entity = new DayItemBean( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // timeDesc
            cursor.getShort(offset + 2) != 0, // inOrOut
            cursor.getLong(offset + 3) // amount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DayItemBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTimeDesc(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setInOrOut(cursor.getShort(offset + 2) != 0);
        entity.setAmount(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DayItemBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DayItemBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DayItemBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
