package com.dixon.bookkeeping.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dixon.bookkeeping.bean.TotalBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TOTAL_BEAN".
*/
public class TotalBeanDao extends AbstractDao<TotalBean, Long> {

    public static final String TABLENAME = "TOTAL_BEAN";

    /**
     * Properties of entity TotalBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Count = new Property(1, int.class, "count", false, "COUNT");
        public final static Property TotalAmount = new Property(2, long.class, "totalAmount", false, "TOTAL_AMOUNT");
    }


    public TotalBeanDao(DaoConfig config) {
        super(config);
    }
    
    public TotalBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TOTAL_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"COUNT\" INTEGER NOT NULL ," + // 1: count
                "\"TOTAL_AMOUNT\" INTEGER NOT NULL );"); // 2: totalAmount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TOTAL_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TotalBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getCount());
        stmt.bindLong(3, entity.getTotalAmount());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TotalBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getCount());
        stmt.bindLong(3, entity.getTotalAmount());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public TotalBean readEntity(Cursor cursor, int offset) {
        TotalBean entity = new TotalBean( //
            cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // count
            cursor.getLong(offset + 2) // totalAmount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TotalBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setCount(cursor.getInt(offset + 1));
        entity.setTotalAmount(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TotalBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TotalBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TotalBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
